### PR TITLE
Update en.yml

### PR DESCRIPTION
**Pull request by jenniferward**
Updating word "Set" to be more in line with French and Italian terms

### CODE REVIEW

**Comment by ahankinson** [comment]
I think the key should change as well -- `set` -> `material_group`. This will then need to be changed in Muscat so tagging @xhero

**Comment by xhero** [comment]
who wants to make a pr for muscat? :P

**Comment by ahankinson** [comment]
I can

**Comment by xhero** [comment]
don't worry, I will make a small commit when I merge this!

**Pull request merged**
